name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"
      - name: Build docker image
        run: ./scripts/buildprod.sh
      - name: Setup goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest
      - name: Run goose migrations
        run: ./scripts/migrateup.sh
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      - name: Build Docker image and Push to GCP
        run: gcloud builds submit --tag europe-central2-docker.pkg.dev/notely-466718/notely-ar-repo/notely:latest .
      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image europe-central2-docker.pkg.dev/notely-466718/notely-ar-repo/notely:latest --region europe-central2 --allow-unauthenticated --project notely-466718 --max-instances=4